### ISSUE TITLE
Desarrollo de los factories de user

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/audiophone-api#1]
se debe desarrollar un proceso de migracion que se conecte a la BD. y que cree solamente la tabla de usuarios. Como en el siguiente modelo en la tabla usuarios.

![Diagrama de clases actualizado](https://user-images.githubusercontent.com/30984939/77823199-9515da80-70cf-11ea-9a33-f16c06276cc7.png)

**Comment by Martalf** [comment]
se creó la migración y crea la tabla en la base de datos audiophoneapi
